### ISSUE TITLE
Generating development_dependencies_install.md as development_dependencies_install.html で失敗する

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#172]
Development Dependencies Install の HTML の生成時に失敗する

```bash
Generating development_dependencies_install.md as development_dependencies_install.html
/Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/markdown.rb:143:in `block in generate_index': undefined method `[]=' for nil:NilClass (NoMethodError)
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/markdown.rb:142:in `tap'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/markdown.rb:142:in `generate_index'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/markdown.rb:26:in `render'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:206:in `block in generate_guide'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:195:in `open'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:195:in `generate_guide'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:144:in `block in generate_guides'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:142:in `each'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:142:in `generate_guides'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:97:in `generate'
	from rails_guides.rb:63:in `<main>'
rake aborted!
Command failed with status (1): [/Users/yasulab/.rbenv/versions/2.1.3/bin/r...]
/Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/Rakefile:11:in `block (3 levels) in <top (required)>'
/Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/Rakefile:23:in `block (3 levels) in <top (required)>'
Tasks: TOP => guides:generate:html
(See full trace by running task with --trace)
```

該当箇所 in `markdown.rb`:

```ruby
def generate_index
        if @headings_for_index.present?
          raw_index = ''
          @headings_for_index.each do |level, node, label|
            if level == 1
              raw_index += "1. [#{label}](##{node[:id]})\n"
            elsif level == 2
              raw_index += "    * [#{label}](##{node[:id]})\n"
            end
          end

          # ココ↓
          @index = Nokogiri::HTML.fragment(engine.render(raw_index)).tap do |doc|
            doc.at('ol')[:class] = 'chapters'
          end.to_html

          @index = <<-INDEX.html_safe
          <div id="subCol">
            <h3 class="chapter"><img src="images/chapters_icon.gif" alt="" />目次</h3>
            #{@index}
          </div>
          INDEX
        end
      end
```

**Comment by yasulab** [comment]
GTTの不具合でした :sweat_drops: お騒がせしました :bow: :sweat_drops:
