### ISSUE TITLE
bundle exec rake guides:generate:dash で生成できなくなった問題の調査・対応

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#307]
久しぶりに dash のRakeタスクを実行したら生成できなくなってしまった... 😭 
Dash 便利なので生成できるようにしたい🤔

```sh
╭─○ yasulab ‹2.4.0› ~/railsguides.jp/guides
╰─○ bundle exec rake guides:generate:dash
/Users/yasulab/.rbenv/versions/2.4.0/bin/ruby rails_guides.rb
Generating 2_3_release_notes.md as 2_3_release_notes.html
/Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:233:in `read': No such file or directory @ rb_sysopen - /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/../source/references.yml (Errno::ENOENT)
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:233:in `yml'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:237:in `references?'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:222:in `block in generate_guide'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:212:in `open'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:212:in `generate_guide'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:161:in `block in generate_guides'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:159:in `each'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:159:in `generate_guides'
	from /Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/rails_guides/generator.rb:98:in `generate'
	from rails_guides.rb:63:in `<main>'
rake aborted!
Command failed with status (1): [/Users/yasulab/.rbenv/versions/2.4.0/bin/r...]
/Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/Rakefile:21:in `block (3 levels) in <top (required)>'
/Users/yasulab/src/github.com/yasslab/railsguides.jp/guides/Rakefile:39:in `block (3 levels) in <top (required)>'
/Users/yasulab/.rbenv/versions/2.4.0/bin/bundle:22:in `load'
/Users/yasulab/.rbenv/versions/2.4.0/bin/bundle:22:in `<main>'
Tasks: TOP => guides:generate:html
(See full trace by running task with --trace)
```

**Comment by yasulab** [comment]
あ、エラーメッセージみたら僕の実行方法が間違っているだけっぽい気がしてきた (環境変数が足りていないだけかも) 💦

**Comment by yasulab** [comment]
すみません、僕が実行方法を間違えてただけでした 🙇 

- x `bundle exec rake guides:generate:dash`
- o `bundle exec rake guides:generate:dash GUIDES_LANGUAGE=ja`
