### ISSUE TITLE
rake assets:precompile で invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by okkez** [yasslab/railsguides.jp#608]
README.md に書いてある手順で既存のドキュメントを確認しようとすると以下のようなエラーが出ました。

```
$ bundle exec rake assets:precompile
Configuration file: /home/kenji/ruby/railsguides.jp/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
           Cleaner: Nothing to do for ./_site.
           Cleaner: Nothing to do for ./guides/output/ja/.jekyll-metadata.
           Cleaner: Nothing to do for .sass-cache.
/home/kenji/.rbenv/versions/2.4.1/bin/ruby rails_guides.rb
Generating contributing_to_ruby_on_rails.md as contributing_to_ruby_on_rails.html
/home/kenji/ruby/railsguides.jp/guides/rails_guides/markdown.rb:72:in `extract_raw_header_and_body': invalid byte sequence in US-ASCII (ArgumentError)
        from /home/kenji/ruby/railsguides.jp/guides/rails_guides/markdown_ja.rb:8:in `render'
        from /home/kenji/ruby/railsguides.jp/guides/rails_guides/generator_ja.rb:70:in `block in generate_guide'
        from /home/kenji/ruby/railsguides.jp/guides/rails_guides/generator_ja.rb:48:in `open'
        from /home/kenji/ruby/railsguides.jp/guides/rails_guides/generator_ja.rb:48:in `generate_guide'
        from /home/kenji/ruby/railsguides.jp/guides/rails_guides/generator.rb:93:in `block in generate_guides'
        from /home/kenji/ruby/railsguides.jp/guides/rails_guides/generator.rb:91:in `each'
        from /home/kenji/ruby/railsguides.jp/guides/rails_guides/generator.rb:91:in `generate_guides'
        from /home/kenji/ruby/railsguides.jp/guides/rails_guides/generator.rb:39:in `generate'
        from /home/kenji/ruby/railsguides.jp/guides/rails_guides/generator_ja.rb:22:in `generate'
        from rails_guides.rb:30:in `<main>'
rake aborted!
Command failed with status (1): [/home/kenji/.rbenv/versions/2.4.1/bin/ruby...]
/home/kenji/ruby/railsguides.jp/yasslab/Rakefile:77:in `block (3 levels) in <top (required)>'
/home/kenji/ruby/railsguides.jp/yasslab/Rakefile:12:in `block (3 levels) in <top (required)>'
/home/kenji/ruby/railsguides.jp/yasslab/Rakefile:4:in `chdir'
/home/kenji/ruby/railsguides.jp/yasslab/Rakefile:4:in `block (2 levels) in <top (required)>'
/home/kenji/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/home/kenji/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
Tasks: TOP => guides:generate:html
(See full trace by running task with --trace)
```
以下のコマンドを実行すると、コマンドに失敗せず最後まで実行できたのですが、これはこれでよいのでしょうか？

```
$ env RUBYOPT="-Eutf-8:utf-8" bundle exec rake assets:precompile
```

jekyll 方面でよく質問されているエラーであるように見えましたが、jekyll はよくわからないので質問させてもらいました。

**Comment by yasulab** [comment]
報告ありがとうございます! 先ほどREADMEをもう少し詳しく書いてもらいましたが、こちらの手順で進めるといかがでしょうか? 🤔 https://github.com/yasslab/railsguides.jp/pull/607

ちなみに成功すると次のようなログになります。こちらもご参考になれば幸いです 🙏 

```bash
╭─○ yasulab ‹2.4.1› ~/railsguides.jp
╰─○ bundle exec rake assets:precompile                                                 master ✓ ±
Configuration file: /Users/yasulab/src/github.com/yasslab/railsguides.jp/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
           Cleaner: Removing ./_site...
           Cleaner: Nothing to do for ./guides/output/ja/.jekyll-metadata.
           Cleaner: Nothing to do for .sass-cache.
/Users/yasulab/.rbenv/versions/2.4.1/bin/ruby rails_guides.rb
Generating active_model_basics.md as active_model_basics.html
Generating index.html.erb as index.html
Generating constant_autoloading_and_reloading.md as constant_autoloading_and_reloading.html
Generating active_job_basics.md as active_job_basics.html
Generating development_dependencies_install.md as development_dependencies_install.html
Generating routing.md as routing.html
Generating i18n.md as i18n.html
Generating action_controller_overview.md as action_controller_overview.html
Generating 4_2_release_notes.md as 4_2_release_notes.html
Generating 3_0_release_notes.md as 3_0_release_notes.html
Generating contributing_to_ruby_on_rails.md as contributing_to_ruby_on_rails.html
Generating initialization.md as initialization.html
Generating active_record_validations.md as active_record_validations.html
Generating generators.md as generators.html
Generating working_with_javascript_in_rails.md as working_with_javascript_in_rails.html
Generating 5_1_release_notes.md as 5_1_release_notes.html
Generating 2_3_release_notes.md as 2_3_release_notes.html
Generating credits.html.erb as credits.html
Generating active_record_basics.md as active_record_basics.html
Generating caching_with_rails.md as caching_with_rails.html
Generating maintenance_policy.md as maintenance_policy.html
Generating active_support_core_extensions.md as active_support_core_extensions.html
Generating action_cable_overview.md as action_cable_overview.html
Generating layout.html.erb as layout.html
Generating active_record_migrations.md as active_record_migrations.html
Generating 3_1_release_notes.md as 3_1_release_notes.html
Generating profiling.md as profiling.html
Generating 5_0_release_notes.md as 5_0_release_notes.html
Generating 2_2_release_notes.md as 2_2_release_notes.html
Generating active_support_instrumentation.md as active_support_instrumentation.html
Generating api_documentation_guidelines.md as api_documentation_guidelines.html
Generating active_record_callbacks.md as active_record_callbacks.html
Generating rails_application_templates.md as rails_application_templates.html
Generating testing.md as testing.html
Generating upgrading_ruby_on_rails.md as upgrading_ruby_on_rails.html
Generating _welcome.html.erb as _welcome.html
Generating _license.html.erb as _license.html
Generating nested_model_forms.md as nested_model_forms.html
Generating getting_started.md as getting_started.html
Generating 3_2_release_notes.md as 3_2_release_notes.html
Generating action_mailer_basics.md as action_mailer_basics.html
Generating 4_0_release_notes.md as 4_0_release_notes.html
Generating debugging_rails_applications.md as debugging_rails_applications.html
Generating ruby_on_rails_guides_guidelines.md as ruby_on_rails_guides_guidelines.html
Generating policy.html.erb as policy.html
Generating plugins.md as plugins.html
Generating active_record_querying.md as active_record_querying.html
Generating autoloading_and_reloading_constants.md as autoloading_and_reloading_constants.html
Generating association_basics.md as association_basics.html
Generating 4_1_release_notes.md as 4_1_release_notes.html
Generating active_storage_overview.md as active_storage_overview.html
Generating action_view_overview.md as action_view_overview.html
Generating api_app.md as api_app.html
Generating options.html.erb as options.html
Generating asset_pipeline.md as asset_pipeline.html
Generating layouts_and_rendering.md as layouts_and_rendering.html
Generating rails_on_rack.md as rails_on_rack.html
Generating engines.md as engines.html
Generating security.md as security.html
Generating configuring.md as configuring.html
Generating form_helpers.md as form_helpers.html
Generating command_line.md as command_line.html
JEKYLL_ENV=production bundle exec jekyll build
Configuration file: /Users/yasulab/src/github.com/yasslab/railsguides.jp/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
            Source: ./guides/output/ja
       Destination: ./_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.278 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

**Comment by okkez** [comment]
解決につながるかどうかわかりませんが、手元でエラーが出る場合の状況を調べてみました。

```
$ uname -a
Linux genbu 4.14.0-3-amd64 #1 SMP Debian 4.14.13-1 (2018-01-14) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux unstable (sid)
Release:        unstable
Codename:       sid
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
$ env | grep LANG
GDM_LANG=ja_JP.UTF-8
LANG=ja_JP.UTF-8
$ bundle --version
Bundler version 1.16.1
$ bundle install
$ bundle check
Your Gemfile lists the gem puma (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem rack-cache (~> 1.2) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem sdoc (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem redcarpet (~> 3.2.3) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem w3c_validators (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem kindlerb (~> 1.2.0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
The Gemfile's dependencies are satisfied
$ bundle exec rake assets:precompile
(エラーの内容は最初のコメントと同じ)
```

```
$ env RUBYOPT="-Eutf-8:utf-8" bundle exec rake assets:precompile
```

↑のように `RUBYOPT="-Eutf-8:utf-8"` を付けて実行すると紹介してもらった成功時のログと同じログが出ました。

----
少しコードを追ってみました。

スタックトレースによると[ここ](https://github.com/yasslab/railsguides.jp/blob/master/guides/rails_guides/markdown_ja.rb#L33)でエラーが発生していました。
`@raw_body` は [ここ](https://github.com/yasslab/railsguides.jp/blob/master/guides/rails_guides/generator_ja.rb#L63) で読み込まれていて、デバッグメッセージを仕込むと、この時点で読み込まれた文字列が uS-ASCII になってしまっていました。
また、この時点で `Encoding.default_external` は `US-ASCII` になっていました。
なお、`rake assets:precompile` で `ruby "rails_guides.rb"` を実行する直前の `Encoding.default_external` は `UTF-8` でした。

以上から考えると、何らかの理由でRakeタスク内で別プロセスとして起動される `ruby "rails_guides.rb"` に `Encoding.default_external` の値が引き継がれていないのが原因だと思います。

よって、以下のように強制的にエンコーディングをUTF-8に指定するのが最も確実な方法だと思います。
ちなみに、単純に `ruby` -> `load` に置き換えても動きます。
💭 jekyll 関係なかった

```diff
$ git diff
diff --git a/yasslab/Rakefile b/yasslab/Rakefile
index 01b7cccb88..3eb964cece 100644
--- a/yasslab/Rakefile
+++ b/yasslab/Rakefile
@@ -74,7 +74,7 @@ namespace :guides do
     desc "Generate HTML guides"
     task html: :encoding do
       ENV["WARNINGS"] = "1" # authors can't disable this
-      ruby "rails_guides.rb"
+      ruby "-Eutf-8:utf-8", "rails_guides.rb"
     end
 
     desc "Generate .mobi file. The kindlegen executable must be in your PATH. You can get it for free from http://www.amazon.com/gp/feature.html?docId=1000765211"
```

**Comment by okkez** [comment]
`encoding` タスクで `ENV[env_var] = "en_US.UTF-8"` と en_US.UTF-8 をハードコーディングしているのがまずいみたいです。
自分の手元だとDebian installerで日本語を指定してセットアップしたので locale に en_US.UTF-8 がありませんでした。
試しに en_US.UTF-8 を追加してから `bundle exec rake assets:precompile` を実行してみると、問題なく最後まで実行することができました。
en_US.UTF-8 を消したら、失敗する状態に戻りました。なので、システムの locale に en_US.UTF-8 が無いと環境変数で指定してもRubyのエンコーディングまわりの設定には反映されないみたいです。

一つ上のコメントで示した通り、明示的に`-Eutf-8:utf-8`を指定するのが最もポータブルな書き方だと思います。

**Comment by yasulab** [comment]
> ちなみに、単純に ruby -> load に置き換えても動きます。

具体的な調査とコメントありがとうございます! 😸 

原著のRakefileをそのまま活用しているためRailsガイドでも `ruby` を使っていますが、`load` に書き換えてもよそうですね🤔 とりあえず PR を出してみました 🔧 💨 https://github.com/yasslab/railsguides.jp/pull/660

原著でも同様の問題が発生すると思うので、原著にプルリクエストを送っていただいても良いかもしれないですね! 😊

**Comment by yasulab** [comment]
> 原著でも同様の問題が発生すると思うので、原著にプルリクエストを送っていただいても良いかもしれないですね! 😊

ちなみに原著へのプルリクエストは @okkez さんの方でご対応されますか? 🤔

**Comment by okkez** [comment]
はい。やっときますー。

https://github.com/yasslab/railsguides.jp/blob/master/yasslab/Rakefile#L60 にあるコメントのように非UTF-8環境だと `Encoding.default_external` が UTF-8 にならないと思うので load だと動かない環境があるように思いました。
というのを裏を取ってからコメントしようと思ってたんですが、間に合わなかった 😅

**Comment by yasulab** [comment]
コメントありがとうございます! では原著への PR の方はよろしくお願いします 😸
